//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELM.ELMData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskInformation
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.TimeSpan> InTime { get; set; }
        public Nullable<System.DateTime> PermissionDate { get; set; }
        public string PermissionType { get; set; }
        public Nullable<bool> IsTaskCreated { get; set; }
        public string TaskID { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
    }
}
